// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package redis

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of Redis replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each Redis replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="1Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// Reserved addresses for the endpoints `external: true` publishes. Each entry pins one endpoint to an address held by an IPAddressClaim, so the address survives a rebuild of this application. Empty lets the load balancer assign any free address, as before.
	// +kubebuilder:default:={}
	ExternalIPs []ExternalIP `json:"externalIPs,omitempty"`
	// Redis major version to deploy
	// +kubebuilder:default:="v8"
	Version Version `json:"version"`
	// TLS configuration. TLS is opt-in and is not inferred from `external`.
	// +kubebuilder:default:={}
	Tls TLS `json:"tls,omitempty"`
	// Enable password generation.
	// +kubebuilder:default:=true
	AuthEnabled bool `json:"authEnabled"`
}

type ExternalIP struct {
	// Name of an IPAddressClaim in this namespace whose address the endpoint should wear. Until the claim binds, the endpoint keeps whatever address the load balancer assigned.
	Claim string `json:"claim"`
	// Which external endpoint to pin. `master` is the Sentinel-elected master, the endpoint `external: true` publishes, and is the default.
	Target string `json:"target,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type TLS struct {
	// Maps to the Redis `tls-auth-clients` directive. Defaults to `no` — the server certificate is presented but client certificates are not validated. `yes` requires a client certificate signed by this release's CA, which the platform does not issue. Changing it restarts the Redis and Sentinel pods, because the directive is read from the config file once at startup.
	AuthClients AuthClients `json:"authClients,omitempty"`
	// Enable TLS for Redis and Sentinel connections. Disabled unless set. Enabling it moves Redis and Sentinel to a TLS-only listener, so existing plaintext clients must be migrated at the same time. Encryption is provided by the redis-operator fork that mounts the certificate Secret into both Redis and Sentinel pods at `/tls`.
	Enabled *bool `json:"enabled,omitempty"`
}

// +kubebuilder:validation:Enum="no";"optional";"yes"
type AuthClients string

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v8";"v7"
type Version string
