// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package vpc

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Subnets of a VPC
	// +kubebuilder:default:={}
	Subnets []Subnet `json:"subnets,omitempty"`
}

type Subnet struct {
	// IP address range
	Cidr string `json:"cidr,omitempty"`
	// Subnet name
	Name string `json:"name"`
}
