// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package vpc

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Subnets of a VPC
	// +kubebuilder:default:={}
	Subnets []Subnet `json:"subnets,omitempty"`
}

type Subnet struct {
	// IP address range
	Cidr string `json:"cidr,omitempty"`
	// Subnet name
	Name string `json:"name"`
}
