// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package rabbitmq

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of RabbitMQ replicas.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each RabbitMQ replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// RabbitMQ major.minor version to deploy
	// +kubebuilder:default:="v4.2"
	Version Version `json:"version"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Virtual hosts configuration map.
	// +kubebuilder:default:={}
	Vhosts map[string]Vhost `json:"vhosts,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Roles struct {
	// List of admin users.
	Admin []string `json:"admin,omitempty"`
	// List of readonly users.
	Readonly []string `json:"readonly,omitempty"`
}

type User struct {
	// Password for the user.
	Password string `json:"password,omitempty"`
}

type Vhost struct {
	// Virtual host roles list.
	Roles Roles `json:"roles"`
}

// +kubebuilder:validation:Enum="nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v4.2";"v4.1";"v4.0";"v3.13"
type Version string
