apiVersion: v2
name: cozy-tls
description: TLS certificate chain sub-chart for managed services
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
