package fluxshardoperator

import (
	"slices"
	"testing"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// fluxAIODeployment models the relevant shape of the flux-aio "flux"
// Deployment generated by timoni (internal/fluxinstall/manifests/fluxcd.yaml).
func fluxAIODeployment() *appsv1.Deployment {
	return &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "flux",
			Namespace: "cozy-fluxcd",
			Labels: map[string]string{
				"app.kubernetes.io/name":    "flux",
				"app.kubernetes.io/version": "v2.8.0",
			},
		},
		Spec: appsv1.DeploymentSpec{
			Template: corev1.PodTemplateSpec{
				Spec: corev1.PodSpec{
					HostNetwork:        true,
					DNSPolicy:          corev1.DNSClusterFirstWithHostNet,
					ServiceAccountName: "flux",
					PriorityClassName:  "system-cluster-critical",
					Tolerations: []corev1.Toleration{
						{Key: "node.kubernetes.io/not-ready", Operator: corev1.TolerationOpExists},
					},
					Volumes: []corev1.Volume{
						{Name: "tmp", VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}}},
						{Name: "data", VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}}},
					},
					Containers: []corev1.Container{
						{Name: "source-controller", Image: "ghcr.io/fluxcd/source-controller:v1.8.0"},
						{
							Name:  "helm-controller",
							Image: "ghcr.io/fluxcd/helm-controller:v1.5.0",
							Args: []string{
								"--watch-all-namespaces",
								"--log-level=info",
								"--enable-leader-election=false",
								"--metrics-addr=:9795",
								"--health-addr=:9796",
								"--watch-label-selector=!sharding.fluxcd.io/key",
								"--concurrent=5",
								"--requeue-dependency=30s",
								"--events-addr=http://localhost:9690",
								"--feature-gates=ExternalArtifact=true",
							},
							Env: []corev1.EnvVar{
								{Name: "SOURCE_CONTROLLER_LOCALHOST", Value: "localhost:9790"},
								{Name: "SOURCE_WATCHER_LOCALHOST", Value: "localhost:9691"},
								{Name: "RUNTIME_NAMESPACE", ValueFrom: &corev1.EnvVarSource{
									FieldRef: &corev1.ObjectFieldSelector{FieldPath: "metadata.namespace"},
								}},
								{Name: "TUF_ROOT", Value: "/tmp/.sigstore"},
							},
							VolumeMounts: []corev1.VolumeMount{{Name: "tmp", MountPath: "/tmp"}},
						},
						{Name: "notification-controller", Image: "ghcr.io/fluxcd/notification-controller:v1.8.0"},
					},
				},
			},
		},
	}
}

func TestBuildShardDeployment(t *testing.T) {
	cfg := &Config{
		FluxNamespace:   "cozy-fluxcd",
		ShardCount:      3,
		ShardConcurrent: 9,
		ShardResources: corev1.ResourceRequirements{
			Requests: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("100m")},
			Limits:   corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("1Gi")},
		},
	}

	dep, err := BuildShardDeployment(fluxAIODeployment(), 2, cfg)
	if err != nil {
		t.Fatal(err)
	}

	if dep.Name != "helm-controller-shard2" || dep.Namespace != "cozy-fluxcd" {
		t.Fatalf("unexpected object meta: %s/%s", dep.Namespace, dep.Name)
	}
	if dep.Labels[ManagedByLabel] != ManagedByValue {
		t.Fatalf("managed-by label missing: %v", dep.Labels)
	}
	if dep.Labels["app.kubernetes.io/version"] != "v2.8.0" {
		t.Fatalf("version label not inherited from flux-aio: %v", dep.Labels)
	}
	if dep.Spec.Strategy.Type != appsv1.RecreateDeploymentStrategyType {
		t.Fatalf("shard rollout must be Recreate, got %s", dep.Spec.Strategy.Type)
	}
	if *dep.Spec.Replicas != 1 {
		t.Fatalf("expected 1 replica, got %d", *dep.Spec.Replicas)
	}

	ps := dep.Spec.Template.Spec
	if ps.HostNetwork || ps.DNSPolicy != corev1.DNSClusterFirst {
		t.Fatalf("host networking must be sanitised away: hostNetwork=%v dnsPolicy=%s", ps.HostNetwork, ps.DNSPolicy)
	}
	if len(ps.Tolerations) != 0 {
		t.Fatalf("flux-aio bootstrap tolerations must be dropped: %v", ps.Tolerations)
	}
	if ps.ServiceAccountName != "flux" || ps.PriorityClassName != "system-cluster-critical" {
		t.Fatalf("flux pod identity must be inherited: sa=%s prio=%s", ps.ServiceAccountName, ps.PriorityClassName)
	}
	if len(ps.Containers) != 1 || ps.Containers[0].Name != "helm-controller" {
		t.Fatalf("only the helm-controller container must survive: %v", ps.Containers)
	}
	if len(ps.Volumes) != 1 || ps.Volumes[0].Name != "tmp" {
		t.Fatalf("only volumes mounted by helm-controller must survive: %v", ps.Volumes)
	}

	hc := ps.Containers[0]
	if hc.Image != "ghcr.io/fluxcd/helm-controller:v1.5.0" {
		t.Fatalf("image must be inherited from flux-aio: %s", hc.Image)
	}
	if !slices.Contains(hc.Args, "--watch-label-selector=sharding.fluxcd.io/key=shard2") {
		t.Fatalf("shard watch selector missing: %v", hc.Args)
	}
	if !slices.Contains(hc.Args, "--concurrent=9") {
		t.Fatalf("concurrent override missing: %v", hc.Args)
	}
	if !slices.Contains(hc.Args, "--feature-gates=ExternalArtifact=true") {
		t.Fatalf("unrelated args must be preserved: %v", hc.Args)
	}
	for _, arg := range hc.Args {
		if arg == "--watch-label-selector=!sharding.fluxcd.io/key" ||
			arg == "--concurrent=5" ||
			arg == "--events-addr=http://localhost:9690" {
			t.Fatalf("unsanitised arg leaked through: %s", arg)
		}
	}

	for _, e := range hc.Env {
		if e.Name == "SOURCE_CONTROLLER_LOCALHOST" || e.Name == "SOURCE_WATCHER_LOCALHOST" {
			t.Fatalf("localhost cross-container env leaked through: %s", e.Name)
		}
	}
	envNames := make([]string, 0, len(hc.Env))
	for _, e := range hc.Env {
		envNames = append(envNames, e.Name)
	}
	if !slices.Contains(envNames, "RUNTIME_NAMESPACE") || !slices.Contains(envNames, "TUF_ROOT") {
		t.Fatalf("regular env must be preserved: %v", envNames)
	}

	if hc.Resources.Limits.Memory().String() != "1Gi" {
		t.Fatalf("resources override not applied: %v", hc.Resources)
	}
}

func TestBuildShardDeploymentInheritsResourcesWhenUnset(t *testing.T) {
	flux := fluxAIODeployment()
	flux.Spec.Template.Spec.Containers[1].Resources = corev1.ResourceRequirements{
		Requests: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("123m")},
	}
	dep, err := BuildShardDeployment(flux, 0, &Config{FluxNamespace: "cozy-fluxcd", ShardConcurrent: 5})
	if err != nil {
		t.Fatal(err)
	}
	if dep.Spec.Template.Spec.Containers[0].Resources.Requests.Cpu().String() != "123m" {
		t.Fatalf("cloned resources must be kept when no override is configured: %v",
			dep.Spec.Template.Spec.Containers[0].Resources)
	}
}

func TestBuildShardDeploymentMissingContainer(t *testing.T) {
	flux := fluxAIODeployment()
	flux.Spec.Template.Spec.Containers = flux.Spec.Template.Spec.Containers[:1]
	if _, err := BuildShardDeployment(flux, 0, &Config{FluxNamespace: "cozy-fluxcd"}); err == nil {
		t.Fatal("expected an error when the helm-controller container is missing")
	}
}

func TestParseShardDeploymentIndex(t *testing.T) {
	if idx, ok := ParseShardDeploymentIndex("helm-controller-shard4"); !ok || idx != 4 {
		t.Fatalf("ParseShardDeploymentIndex(helm-controller-shard4) = %d,%v", idx, ok)
	}
	for _, name := range []string{"helm-controller-shard", "flux-tenants", "helm-controller-tenants"} {
		if _, ok := ParseShardDeploymentIndex(name); ok {
			t.Fatalf("ParseShardDeploymentIndex(%s) must fail", name)
		}
	}
}
