## @section Image
## @param image.repository LINSTOR GUI container image repository
## @param image.tag LINSTOR GUI container image tag (digest recommended)
image:
  repository: ghcr.io/cozystack/cozystack/linstor-gui
  tag: 2.3.0@sha256:f8dd285680c5106fc5a454cdcf309891f1a65a97b81e8ec7b9e029ea0b28d98c
## @section Deployment
## @param replicas Number of linstor-gui replicas
replicas: 1
## @section LINSTOR controller connection
## @param linstor.endpoint In-cluster URL of the LINSTOR controller REST API (HTTPS, mTLS)
## @param linstor.clientSecret Kubernetes Secret with `tls.crt`, `tls.key`, `ca.crt` used as the mTLS client certificate against the LINSTOR controller. Created by the `linstor` package.
linstor:
  endpoint: "https://linstor-controller.cozy-linstor.svc:3371"
  clientSecret: "linstor-client-tls"
