{{- if .Values.bucket.bucketInfo }}
{{- $bucketInfo := fromJson .Values.bucket.bucketInfo }}
{{- $secretS3 := dig "spec" "secretS3" dict $bucketInfo }}
{{- if $secretS3 }}
{{- $accessKeyID := index $secretS3 "accessKeyID" }}
{{- $accessSecretKey := index $secretS3 "accessSecretKey" }}
{{- $endpoint := index $secretS3 "endpoint" }}
{{- $bucketName := dig "spec" "bucketName" "" $bucketInfo }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harbor.fullnameOverride }}-registry-s3
type: Opaque
stringData:
  REGISTRY_STORAGE_S3_ACCESSKEY: {{ $accessKeyID | quote }}
  REGISTRY_STORAGE_S3_SECRETKEY: {{ $accessSecretKey | quote }}
  REGISTRY_STORAGE_S3_REGIONENDPOINT: {{ $endpoint | quote }}
  REGISTRY_STORAGE_S3_BUCKET: {{ $bucketName | quote }}
  REGISTRY_STORAGE_S3_REGION: "us-east-1"
{{- end }}
{{- end }}
