{{- /* COSI BucketInfo is merged at the values root via Flux valuesFrom (no targetPath). */ -}}
{{- with .Values.spec }}
{{- with .secretS3 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.harbor.fullnameOverride }}-registry-s3
type: Opaque
stringData:
  REGISTRY_STORAGE_S3_ACCESSKEY: {{ index . "accessKeyID" | quote }}
  REGISTRY_STORAGE_S3_SECRETKEY: {{ index . "accessSecretKey" | quote }}
  REGISTRY_STORAGE_S3_REGIONENDPOINT: {{ index . "endpoint" | quote }}
  REGISTRY_STORAGE_S3_BUCKET: {{ $.Values.spec.bucketName | quote }}
  REGISTRY_STORAGE_S3_REGION: "us-east-1"
{{- end }}
{{- end }}
