{{- if and .Values.enabled (not (.Values.issuerRef.name | trim)) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cozy-tls.selfsigned-issuer-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cozy-tls.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
