apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-bookworm
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: bookworm
    images.cnpg.io/date: '20260427'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 14
      image: ghcr.io/cloudnative-pg/postgresql:14.22-202604270853-standard-bookworm@sha256:efdda2e4f4d53ddba1ba478c19738dbc63eb3eee697a6beb4f13c5f2cd68856d
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.17-202604270853-standard-bookworm@sha256:b5c9affb267dcee0eaa366bd9987ca7b2429bf8d0bce23f8820533cf697f202d
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.13-202604270853-standard-bookworm@sha256:5e2da2bd8acb33498a155ae0e3d07e277a1ca87ba31ed1d7b668033a84752df4
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.9-202604270853-standard-bookworm@sha256:b054e25c4a813e1c8cf996058bcf9b0e5609e7958e459d42b8e1b5cf55baabd8
