lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v1.3.4@sha256:37f7e552bca0029865d799a737994271c01a55e2d749bc92e808d1cee5209639
  debug: false
  localK8sAPIEndpoint:
    enabled: true
  # nodeSelector for the DaemonSet
  # Talos uses empty value: "node-role.kubernetes.io/control-plane": ""
  # Generic k8s (k3s, kubeadm) uses: "node-role.kubernetes.io/control-plane": "true"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
