lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v1.1.1@sha256:f2c0f41a8d5bdbddc38c4f27f9242e581a3d503e039597866d0899de41fde7bb
  debug: false
  localK8sAPIEndpoint:
    enabled: true
  # nodeSelector for the DaemonSet
  # Talos uses empty value: "node-role.kubernetes.io/control-plane": ""
  # Generic k8s (k3s, kubeadm) uses: "node-role.kubernetes.io/control-plane": "true"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
