// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package kubernetesnodes

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Name of the parent Kubernetes cluster (the `Kubernetes` CR) in the same namespace this node pool attaches to. Required. The pool's CAPI objects are wired to the parent cluster `kubernetes-<cluster>`; the KubernetesNodes CR must be named `<cluster>-<pool>`. The pool name (the part after `<cluster>-`) must not collide with a nodeGroup still managed by the parent kubernetes chart (e.g. the default `md0`), or the render fails on ownership conflict.
	// +kubebuilder:default:=""
	Cluster string `json:"cluster"`
	// StorageClass for the worker node system disk. When empty, the cluster default applies. Worker VMs live-migrate, so their disks need ReadWriteMany — the RWX access mode is supplied by the chosen StorageClass's CDI StorageProfile — and linstor-csi rejects RWX volumes that are not on a DRBD-backed StorageClass, so prefer a replicated/DRBD class.
	// +kubebuilder:default:="replicated"
	StorageClass string `json:"storageClass"`
	// Minimum number of replicas in this pool. Used as the cluster-autoscaler floor.
	// +kubebuilder:default:=0
	MinReplicas int `json:"minReplicas"`
	// Maximum number of replicas in this pool. Used as the cluster-autoscaler ceiling.
	// +kubebuilder:default:=10
	MaxReplicas int `json:"maxReplicas"`
	// Virtual machine instance type.
	// +kubebuilder:default:="u1.medium"
	InstanceType string `json:"instanceType"`
	// System disk size for the worker VM. Carries the Talos OS image (factory.talos.dev raw artifact streamed in by CDI), kubelet state, containerd image cache, and any local-path PVCs.
	// +kubebuilder:default:="20Gi"
	DiskSize resource.Quantity `json:"diskSize"`
	// List of node roles. Each role `r` labels nodes with `node-role.kubernetes.io/<r>`. Use `[ingress-nginx]` for a pool that hosts the tenant ingress-nginx controller.
	// +kubebuilder:default:={}
	Roles []string `json:"roles,omitempty"`
	// Explicit CPU and memory for each worker node, as an alternative to `instanceType` sizing. Optional: when omitted, the node is sized by `instanceType`. When both `cpu` and `memory` are set, they take precedence and `instanceType` is ignored (the instancetype is omitted from the VM, since KubeVirt cannot override an instancetype's CPU/memory). Set both `cpu` and `memory` together or neither; setting only one is rejected at render time.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// List of GPUs to attach (NVIDIA driver requires at least 4 GiB RAM).
	// +kubebuilder:default:={}
	Gpus []GPU `json:"gpus,omitempty"`
	// Per-pool override for `talos.schematicID`, applied to both the worker boot disk image and the Talos installer image. When empty, the cluster-wide `talos.schematicID` applies. A schematic is a fixed set of Talos system extensions, and Talos refuses to finish booting when an extension service in it cannot start: `ext-nvidia-persistenced` and `ext-nvidia-cdi-gen` require an NVIDIA card, so a pool with no GPU that boots an NVIDIA schematic fails `startAllServices` and reboots roughly every 70 minutes, indefinitely, while still reporting `Ready` (kubelet starts before the failing phase). A cluster mixing GPU and non-GPU pools therefore has no correct cluster-wide value, and this field is what makes it expressible: set the NVIDIA schematic on the GPU pool only. Changing it replaces the pool's boot image and so rolls its workers.
	// +kubebuilder:default:=""
	SchematicID string `json:"schematicID,omitempty"`
	// Kernel modules loaded on every worker in this pool, emitted as Talos `machine.kernel.modules`. A Talos system extension installs a module but does not load it, so an extension-provided driver needs its modules declared here. Leave unset to let the chart decide: a pool holding at least one `nvidia.com/*` GPU gets `nvidia`, `nvidia_uvm`, `nvidia_drm`, `nvidia_modeset` (that order — Talos loads the list in sequence and the last three depend on the first), and any other pool gets nothing. Set a non-empty list to replace the chart's choice entirely, or `[]` to opt out and emit no modules even on a GPU pool. The module still has to be in the image: which extension supplies it is set by `talos.schematicID`, and on Blackwell (GB202) it must be the open-kernel-modules extension. Changing this on a pool that already has running workers does not reach them: the `TalosConfigTemplate` its MachineDeployment references has a fixed name, so rewriting the template leaves `spec.template` untouched, CAPI starts no rollout, and a running Machine keeps the machine config it booted with. Replace the pool's Machines to apply it. Unlike `schematicID`, which changes the boot image and therefore rolls the pool by itself. Note the automatic set keys on the `nvidia.com/` resource prefix alone: nothing cross-checks that the effective schematic actually carries those modules, so declaring a module the image does not ship is possible. On Talos v1.13 such a module leaves its controller retrying rather than failing the boot, so the symptom is a missing driver, not a dead node.
	KernelModules []KernelModule `json:"kernelModules,omitempty"`
	// Kubelet resource reservations for this pool.
	// +kubebuilder:default:={}
	Kubelet Kubelet `json:"kubelet,omitempty"`
	// Maximum number of unhealthy nodes tolerated in this pool before remediation is paused. The MachineHealthCheck admission webhook accepts either a bare integer ("0", "1", ...) or a percentage ("0%", "50%"); bare numeric strings are rejected, so the safer default is a percentage. Drop to "0%" once the pool is stable.
	// +kubebuilder:default:="50%"
	MaxUnhealthy string `json:"maxUnhealthy"`
	// Maximum time a Machine is allowed to spend reaching the Ready condition before it is remediated. Raise for slow first boots (Talos image fetch from factory.talos.dev or a busy storage class on the kubevirt-csi PVC populator).
	// +kubebuilder:default:="10m"
	NodeStartupTimeout string `json:"nodeStartupTimeout"`
	// Kubernetes major.minor version the pool joins. Must match the parent cluster's version and satisfy the Talos<->Kubernetes support matrix against `talos.version`.
	// +kubebuilder:default:="v1.35"
	Version Version `json:"version"`
	// Talos worker image configuration. Keep in sync with the parent cluster's `talos`.
	// +kubebuilder:default:={}
	Talos Talos `json:"talos"`
	// Optional image overrides for air-gapped or rate-limited registries.
	// +kubebuilder:default:={}
	Images Images `json:"images"`
}

type GPU struct {
	// Name of GPU, such as "nvidia.com/AD102GL_L40S".
	Name string `json:"name"`
}

type Images struct {
	// Image used by the talos-reconcile Job (kubectl). Empty falls back to images/kubectl.tag.
	// +kubebuilder:default:=""
	Kubectl string `json:"kubectl,omitempty"`
}

type KernelModule struct {
	// Module name as `modprobe` takes it, e.g. `nvidia_uvm`.
	Name string `json:"name"`
	// Module parameters, each as a bare `key=value` string.
	Parameters []string `json:"parameters,omitempty"`
}

type Kubelet struct {
	// Hard eviction threshold for memory (absolute like 200Mi or percentage like 7%).
	// +kubebuilder:default:="7%"
	EvictionHardMemory string `json:"evictionHardMemory,omitempty"`
	// Soft eviction threshold for memory (absolute like 1Gi or percentage like 10%).
	// +kubebuilder:default:="10%"
	EvictionSoftMemory string `json:"evictionSoftMemory,omitempty"`
	// CPU reserved for kubelet and container runtime. Auto-computed from instanceType if empty.
	KubeReservedCpu string `json:"kubeReservedCpu,omitempty"`
	// Memory reserved for kubelet and container runtime. Auto-computed from instanceType if empty.
	KubeReservedMemory string `json:"kubeReservedMemory,omitempty"`
	// CPU reserved for host OS. Auto-computed from instanceType if empty.
	SystemReservedCpu string `json:"systemReservedCpu,omitempty"`
	// Memory reserved for host OS. Auto-computed from instanceType if empty.
	SystemReservedMemory string `json:"systemReservedMemory,omitempty"`
}

type Resources struct {
	// CPU available.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Talos struct {
	// Base URL of the Talos Image Factory that serves the worker OS disk image (the `openstack-amd64.raw.xz` raw artifact streamed in by CDI over HTTP). Defaults to the public factory. Point at a self-hosted Image Factory, a caching mirror, or an internal HTTP file server for air-gapped, rate-limited, or flaky-egress environments. No trailing slash.
	// +kubebuilder:default:="https://factory.talos.dev"
	ImageFactoryURL string `json:"imageFactoryURL"`
	// OCI repository prefix for the Talos installer image used by the in-guest `talos-reconcile` upgrade Job. Resolved as `<installerRepository>/<schematicID>:<version>`. Defaults to the public factory's installer path. Override for air-gapped or mirrored registries. No trailing slash.
	// +kubebuilder:default:="factory.talos.dev/installer"
	InstallerRepository string `json:"installerRepository"`
	// Talos image-factory schematic ID. Defaults to the cozystack-tested vanilla schematic. Operators using custom schematics (system extensions, kernel args) override here. This pool can override it for itself via the root-level `schematicID`. Constrained to `^[A-Za-z0-9._:-]+$`, applied to the effective value: the ID is interpolated into the worker machine config, which is applied through a shell heredoc. A 64-hex factory digest and the readable path an operator chose on a self-hosted factory or mirror both satisfy it.
	// +kubebuilder:default:="ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515"
	SchematicID string `json:"schematicID"`
	// Talos release used for worker OS image and installer. Must satisfy the chart's Talos<->Kubernetes support matrix against the chosen `version`.
	// +kubebuilder:default:="v1.13.6"
	Version string `json:"version"`
}

// +kubebuilder:validation:Enum="v1.35";"v1.34";"v1.33";"v1.32";"v1.31"
type Version string
