{{- $solver := (index .Values._cluster "solver") | default "http01" }}
{{- $clusterIssuer := (index .Values._cluster "issuer-name") | default "letsencrypt-prod" }}
{{- $ingress := .Values._namespace.ingress }}
{{- $host := .Values._namespace.host }}
{{- $gatewayEnabled := (index .Values._cluster "gateway-enabled") | default "false" }}
{{- if and .Values.grafana.smtp .Values.grafana.smtp.enabled .Values.grafana.smtp.user }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-smtp
  labels:
    app: grafana
type: Opaque
stringData:
  user: {{ .Values.grafana.smtp.user | quote }}
  password: {{ .Values.grafana.smtp.password | quote }}
{{- end }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    database:
      type: postgres
      name: ${GF_DATABASE_NAME}
      host: ${GF_DATABASE_HOST}
      user: ${GF_DATABASE_USER}
      password: ${GF_DATABASE_PASSWORD}
      #ssl_mode: require
    server:
      root_url: "https://{{ printf "grafana.%s" (.Values.host | default $host) }}"
    security:
      admin_user: user
      admin_password: ${GF_PASSWORD}
    plugins:
      allow_loading_unsigned_plugins: "victoriametrics-logs-datasource"
  deployment:
    spec:
      replicas: 2
      template:
        spec:
          containers:
            - name: grafana
              resources: {{- toYaml .Values.grafana.resources | nindent 16 }}
              image: "{{ $.Files.Get "images/grafana.tag" | trim }}"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
              readinessProbe:
                failureThreshold: 3
              env:
              #- name: GF_INSTALL_PLUGINS
              #  value: grafana-worldmap-panel,natel-discrete-panel
              - name: GF_PATHS_PLUGINS
                value: /var/lib/grafana-plugins
              - name: ONCALL_API_URL
                value: http://grafana-oncall-engine:8080
              - name: GF_DATABASE_HOST
                value: "grafana-db-rw:5432"
              - name: GF_DATABASE_PASSWORD
                valueFrom: { secretKeyRef: { name: grafana-db-app, key: password } }
              - name: GF_DATABASE_NAME
                value: "app"
              - name: GF_DATABASE_USER
                value: "app"
              - name: GF_PASSWORD
                valueFrom: { secretKeyRef: { name: grafana-admin-password, key: password } }
              - name: GF_SECURITY_ADMIN_USER
                valueFrom:
                  secretKeyRef:
                    key: user
                    name: grafana-admin-password
              - name: GF_SECURITY_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: grafana-admin-password
              {{- if and .Values.grafana.smtp .Values.grafana.smtp.enabled }}
              {{- if .Values.grafana.smtp.user }}
              - name: GF_SMTP_USER
                valueFrom:
                  secretKeyRef:
                    name: grafana-smtp
                    key: user
              {{- if .Values.grafana.smtp.password }}
              - name: GF_SMTP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: grafana-smtp
                    key: password
              {{- end }}
              {{- end }}
              - name: GF_SMTP_ENABLED
                value: "true"
              - name: GF_SMTP_HOST
                value: {{ .Values.grafana.smtp.host | quote }}
              - name: GF_SMTP_FROM_ADDRESS
                value: {{ .Values.grafana.smtp.from_address | quote }}
              - name: GF_SMTP_FROM_NAME
                value: {{ .Values.grafana.smtp.from_name | default "Grafana" | quote }}
              - name: GF_SMTP_SKIP_VERIFY
                value: {{ .Values.grafana.smtp.skip_verify | default false | quote }}
              - name: GF_SMTP_STARTTLS_POLICY
                value: {{ .Values.grafana.smtp.start_tls_policy | default "OpportunisticStartTLS" | quote }}
              {{- end }}
  {{- if ne $gatewayEnabled "true" }}
  ingress:
    metadata:
      annotations:
        {{- if eq $solver "http01" }}
        acme.cert-manager.io/http01-ingress-ingressclassname: "{{ $ingress }}"
        {{- end }}
        cert-manager.io/cluster-issuer: {{ $clusterIssuer }}
    spec:
      ingressClassName: "{{ $ingress }}"
      rules:
        - host: "{{ printf "grafana.%s" (.Values.host | default $host) }}"
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
      - hosts:
        - "{{ printf "grafana.%s" (.Values.host | default $host) }}"
        secretName: grafana-ingress-tls
  {{- end }}
