piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: 1.32.3@sha256:e2d0af80b88bf6d4adc4846354bab4e61267e0b6549406757a121d6d2e8a812f
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: v1.10.5@sha256:57e26cdadd762a620ee9471db9a400d9dee4f4c74bc0d0a86fd001b5e6390682
