piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: 1.32.3@sha256:d78071fdc33220168e3f2ab112a86208be95898b75268a0c62763b8a04e145ad
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: v1.10.5@sha256:e80ae94d8acd8774cb35715b1f103071ae6cd3160f1ebea915e5e6ee49234448
