piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: 1.33.2@sha256:25f40cdae42295a0501e8826ffb9c0203c45d4b2161566d31708f2031fc33f3f
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: v1.10.6@sha256:54b24c8ac49f009790938c16eb7f3222372f2321e8cd9caa625056006ffc43bd
