---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomFormsPrefill
metadata:
  name: apps.cozystack.io.v1alpha1.redises
spec:
  customizationId: default-/apps.cozystack.io/v1alpha1/redises
  values:
    - path:
        - metadata
        - name
      value: example
{{ include "renderValues" (dict "values" .Values) | indent 4 }}
