---
# == db-autoscaler view cluster role ==
# Aggregated into cozy-tenant-view (and consequently use, admin, super-admin).
# Read-only access to DatabaseHorizontalAutoscaler resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cozy:dbautoscaler:view
  labels:
    rbac.cozystack.io/aggregate-to-tenant-view: "true"
rules:
- apiGroups: ["autoscaling.cozystack.io"]
  resources:
  - databasehorizontalautoscalers
  verbs:
  - get
  - list
  - watch
---
# == db-autoscaler admin cluster role ==
# Aggregated into cozy-tenant-admin (and consequently super-admin).
# Write access to DatabaseHorizontalAutoscaler resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cozy:dbautoscaler:admin
  labels:
    rbac.cozystack.io/aggregate-to-tenant-admin: "true"
rules:
- apiGroups: ["autoscaling.cozystack.io"]
  resources:
  - databasehorizontalautoscalers
  verbs:
  - create
  - update
  - patch
  - delete
