{
 "title": "MongoDB InMemory Details",
 "description": "MongoDB WiredTiger InMemory Details",
 "tags": [ "mongodb" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "job", "label": "Service", "query": { "query": "label_values(mongodb_up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "InMemory Data Size",
   "type": "stat",
   "description": "Amount of data currently stored InMemory in its uncompressed format.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_mongod_wiredtiger_cache_bytes{job=\"$job\", type=\"total\"})"
    }
   ]
  },
  {
   "title": "InMemory Max Data Size",
   "type": "stat",
   "description": "Maximum size the InMemory data can grow to. Configurable via storage.wiredTiger.inMemory.cacheSizeGB.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_mongod_wiredtiger_cache_max_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "InMemory Available",
   "type": "stat",
   "description": "Amount of memory left available for InMemory databases.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(avg(mongodb_mongod_wiredtiger_cache_bytes{job=\"$job\", type=\"total\"})/avg(mongodb_mongod_wiredtiger_cache_max_bytes{job=\"$job\"}))"
    }
   ]
  },
  {
   "title": "InMemory Dirty Pages",
   "type": "stat",
   "description": "Percentage of InMemory pages that have been changed and not yet had the modified data consolidated.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_mongod_wiredtiger_cache_pages{job=\"$job\",type=\"dirty\"})/avg(mongodb_mongod_wiredtiger_cache_pages{job=\"$job\",type=\"total\"})"
    }
   ]
  },
  {
   "title": "InMemory Transactions",
   "type": "timeseries",
   "description": "WiredTiger internal transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (type) (rate(mongodb_mongod_wiredtiger_transactions_total{job=\"$job\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "InMemory Capacity",
   "type": "timeseries",
   "description": "Configured max and current size of the WiredTiger cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(mongodb_mongod_wiredtiger_cache_max_bytes{job=\"$job\"})",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(mongodb_mongod_wiredtiger_cache_bytes{job=\"$job\", type=\"total\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "InMemory Sessions",
   "type": "timeseries",
   "description": "Internal WiredTiger storage engine cursors and sessions currently open.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(mongodb_mongod_wiredtiger_session_open_cursors_total{job=\"$job\"})",
     "legendFormat": "Cursors"
    },
    {
     "expr": "avg(mongodb_mongod_wiredtiger_session_open_sessions_total{job=\"$job\"})",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "InMemory Pages",
   "type": "timeseries",
   "description": "Pages in the WiredTiger cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (type) (mongodb_mongod_wiredtiger_cache_pages{job=\"$job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "InMemory Concurrency Tickets",
   "type": "timeseries",
   "description": "A WiredTiger 'ticket' is assigned for every operation running simultaneously in the storage engine.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (type) (mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{job=\"$job\"}-mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{job=\"$job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "timeseries",
   "description": "Operations queued due to a lock",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (type) (mongodb_mongod_global_lock_current_queue{job=\"$job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "timeseries",
   "description": "Documents per second inserted, updated, deleted or returned.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (state) (rate(mongodb_mongod_metrics_document_total{job=\"$job\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg(rate(mongodb_mongod_op_counters_repl_total{job=\"$job\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{job=\"$job\", type=\"delete\"}[5m]))",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "avg(rate(mongodb_mongod_op_counters_repl_total{job=\"$job\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{job=\"$job\", type=\"update\"}[5m]))",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "avg(rate(mongodb_mongod_op_counters_repl_total{job=\"$job\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{job=\"$job\", type=\"insert\"}[5m]))",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "avg(rate(mongodb_mongod_metrics_ttl_deleted_documents_total{job=\"$job\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{job=\"$job\"}[5m]))",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "InMemory Cache Eviction",
   "type": "timeseries",
   "description": "Number of pages evicted from the WiredTiger cache. The InMemory storage engine only evicts modified pages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(mongodb_mongod_wiredtiger_cache_evicted_total{job=\"$job\",type=\"modified\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{job=\"$job\",type=\"modified\"}[5m]))",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "timeseries",
   "description": "Number of objects scanned (data and index) and documents moved to a new location.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (state) (rate(mongodb_mongod_metrics_query_executor_total{job=\"$job\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg(rate(mongodb_mongod_metrics_record_moves_total{job=\"$job\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{job=\"$job\"}[5m]))",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "description": "Memory page faults. Not necessarily from MongoDB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(mongodb_mongod_extra_info_page_faults_total{job=\"$job\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{job=\"$job\"}[5m]) or rate(mongodb_extra_info_page_faults_total{job=\"$job\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{job=\"$job\"}[5m]))",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}