hami:
  scheduler:
    kubeScheduler:
      image:
        registry: registry.k8s.io
        repository: kube-scheduler
  devicePlugin:
    runtimeClassName: nvidia
    updateStrategy:
      type: OnDelete
    # See https://github.com/Project-HAMi/HAMi/blob/v2.8.1/deployments/charts/hami/values.yaml
    # Each entry: {"name": "node-name", "operatingmode": "hami-core", "devicesplitcount": N, ...}
    nodeConfiguration:
      config: |
        {
          "nodeconfig": []
        }
