{{- $exposeIngress := (index .Values._cluster "expose-ingress") | default "tenant-root" }}
{{- $exposeExternalIPs := (index .Values._cluster "expose-external-ips") | default "" | nospace }}
{{- $exposeIPsList := list }}
{{- range splitList "," $exposeExternalIPs }}
  {{- $ip := . | trim }}
  {{- if $ip }}
    {{- $exposeIPsList = append $exposeIPsList $ip }}
  {{- end }}
{{- end }}
{{- if and (eq $exposeIngress .Release.Namespace) $exposeIPsList }}
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: {{ trimPrefix "tenant-" .Release.Namespace }}-gateway
spec:
  blocks:
  {{- range $exposeIPsList }}
  - cidr: {{ . }}/{{ if contains ":" . }}128{{ else }}32{{ end }}
  {{- end }}
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.namespace": {{ .Release.Namespace | quote }}
      "gateway.networking.k8s.io/gateway-name": cozystack
{{- end }}
