apiVersion: v2
name: cozy-etcd-operator-crds
description: CRDs for the cozystack etcd-operator (etcd-operator.cozystack.io/v1alpha2)
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
