// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package vmdisk

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Defines if disk should be considered optical.
	// +kubebuilder:default:=false
	Optical bool `json:"optical"`
	// The source image location used to create a disk.
	// +kubebuilder:default:={}
	Source Source `json:"source"`
	// The size of the disk allocated for the virtual machine.
	// +kubebuilder:default:="5Gi"
	Storage resource.Quantity `json:"storage"`
	// StorageClass used to store the data.
	// +kubebuilder:default:="replicated"
	StorageClass string `json:"storageClass"`
}

type Source struct {
	// Download image from an HTTP source.
	Http *SourceHTTP `json:"http,omitempty"`
	// Use image by name.
	Image *SourceImage `json:"image,omitempty"`
	// Upload local image.
	Upload *SourceUpload `json:"upload,omitempty"`
}

type SourceHTTP struct {
	// URL to download the image.
	Url string `json:"url"`
}

type SourceImage struct {
	// Name of the image to use (uploaded as "golden image" or from the list: `ubuntu`, `fedora`, `cirros`, `alpine`, `talos`).
	Name string `json:"name"`
}

type SourceUpload struct {
}
