// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package harbor

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Core API server configuration.
	// +kubebuilder:default:={}
	Core Core `json:"core"`
	// PostgreSQL database configuration.
	// +kubebuilder:default:={}
	Database Database `json:"database"`
	// Hostname for external access to Harbor (defaults to 'harbor' subdomain for the tenant host).
	// +kubebuilder:default:=""
	Host string `json:"host,omitempty"`
	// Background job service configuration.
	// +kubebuilder:default:={}
	Jobservice Jobservice `json:"jobservice"`
	// Redis cache configuration.
	// +kubebuilder:default:={}
	Redis Redis `json:"redis"`
	// Container image registry configuration.
	// +kubebuilder:default:={}
	Registry Registry `json:"registry"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Trivy vulnerability scanner configuration.
	// +kubebuilder:default:={}
	Trivy Trivy `json:"trivy"`
}

type Trivy struct {
	// Enable or disable the vulnerability scanner.
	// +kubebuilder:default:=true
	Enabled bool `json:"enabled"`
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
	// Persistent Volume size for vulnerability database cache.
	// +kubebuilder:default:="5Gi"
	Size resource.Quantity `json:"size"`
}

type Jobservice struct {
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
}

type Resources struct {
	// Number of CPU cores allocated.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Amount of memory allocated.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Database struct {
	// Number of database instances.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Persistent Volume size for database storage.
	// +kubebuilder:default:="5Gi"
	Size resource.Quantity `json:"size"`
}

type Redis struct {
	// Number of Redis replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Persistent Volume size for cache storage.
	// +kubebuilder:default:="1Gi"
	Size resource.Quantity `json:"size"`
}

type Core struct {
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
}

type Registry struct {
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
}

// +kubebuilder:validation:Enum="nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string
