{{- $oidcEnabled := index .Values._cluster "oidc-enabled" }}
{{- if eq $oidcEnabled "true" }}
apiVersion: v1
kind: Service
metadata:
  name: linstor-gui-gatekeeper
  labels:
    app.kubernetes.io/instance: linstor-gui
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: cozystack
spec:
  type: ClusterIP
  ports:
    - name: ingress
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: linstor-gui
    app.kubernetes.io/name: gatekeeper
{{- end }}
