apiVersion: v1
kind: Service
metadata:
  name: linstor-gui
  labels:
    {{- include "linstor-gui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "linstor-gui.selectorLabels" . | nindent 4 }}
