{{- if .Values.lineageControllerWebhook.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineage-controller-webhook
  labels:
    app: lineage-controller-webhook
spec:
  replicas: {{ .Values.lineageControllerWebhook.deployment.replicas }}
  selector:
    matchLabels:
      app: lineage-controller-webhook
  template:
    metadata:
      labels:
        app: lineage-controller-webhook
    spec:
      serviceAccountName: lineage-controller-webhook
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: lineage-controller-webhook
      containers:
      - name: lineage-controller-webhook
        image: "{{ .Values.lineageControllerWebhook.image }}"
        args:
        {{- if .Values.lineageControllerWebhook.debug }}
        - --zap-log-level=debug
        {{- else }}
        - --zap-log-level=info
        {{- end }}
        ports:
        - name: webhook
          containerPort: 9443
        volumeMounts:
          - name: webhook-certs
            mountPath: /tmp/k8s-webhook-server/serving-certs
            readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: lineage-controller-webhook-cert
            defaultMode: 0400
{{- end }}