// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package bucket

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Provisions bucket from the `-lock` BucketClass (with object lock enabled).
	// +kubebuilder:default:=false
	Locking bool `json:"locking"`
	// Selects a specific BucketClass by storage pool name.
	// +kubebuilder:default:=""
	StoragePool string `json:"storagePool,omitempty"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
}

type User struct {
	// Whether the user has read-only access.
	Readonly bool `json:"readonly,omitempty"`
}
