// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package bucket

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Provisions bucket from the `-lock` BucketClass (with object lock enabled).
	// +kubebuilder:default:=false
	Locking bool `json:"locking"`
	// Selects a specific BucketClass by storage pool name.
	// +kubebuilder:default:=""
	StoragePool string `json:"storagePool,omitempty"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Name of a SchedulingClass CR (cluster-scoped, group cozystack.io) applied to this application's workloads. When set, takes precedence over any tenant-level schedulingClass. Empty means inherit from the tenant.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:MaxLength=63
	SchedulingClass string `json:"schedulingClass"`
}

type User struct {
	// Whether the user has read-only access.
	Readonly bool `json:"readonly,omitempty"`
}
