snapshot-controller:
  controller:
    replicaCount: 2
    revisionHistoryLimit: 10
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  webhook:
    replicaCount: 2
    revisionHistoryLimit: 10
    hostNetwork: false
    dnsPolicy: ClusterFirst
    tls:
      certManagerIssuerRef:
        name: selfsigned-cluster-issuer
        kind: ClusterIssuer
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
