// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package mongodb

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of MongoDB replicas in replica set.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each MongoDB replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// MongoDB major version to deploy.
	// +kubebuilder:default:="v8"
	Version Version `json:"version"`
	// Enable sharded cluster mode. When disabled, deploys a replica set.
	// +kubebuilder:default:=false
	Sharding bool `json:"sharding"`
	// Configuration for sharded cluster mode.
	// +kubebuilder:default:={}
	ShardingConfig ShardingConfig `json:"shardingConfig"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Databases configuration map.
	// +kubebuilder:default:={}
	Databases map[string]Database `json:"databases,omitempty"`
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
	// Bootstrap configuration.
	// +kubebuilder:default:={}
	Bootstrap Bootstrap `json:"bootstrap"`
}

type Backup struct {
	// Destination path for backups (e.g. s3://bucket/path/).
	// +kubebuilder:default:="s3://bucket/path/to/folder/"
	DestinationPath string `json:"destinationPath,omitempty"`
	// Enable regular backups.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// S3 endpoint URL for uploads.
	// +kubebuilder:default:="http://minio-gateway-service:9000"
	EndpointURL string `json:"endpointURL,omitempty"`
	// Retention policy (e.g. "30d").
	// +kubebuilder:default:="30d"
	RetentionPolicy string `json:"retentionPolicy,omitempty"`
	// Access key for S3 authentication.
	// +kubebuilder:default:=""
	S3AccessKey string `json:"s3AccessKey,omitempty"`
	// Secret key for S3 authentication.
	// +kubebuilder:default:=""
	S3SecretKey string `json:"s3SecretKey,omitempty"`
	// Cron schedule for automated backups.
	// +kubebuilder:default:="0 2 * * *"
	Schedule string `json:"schedule,omitempty"`
}

type Bootstrap struct {
	// Name of backup to restore from.
	// +kubebuilder:default:=""
	BackupName string `json:"backupName"`
	// Whether to restore from a backup.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Timestamp for point-in-time recovery; empty means latest.
	// +kubebuilder:default:=""
	RecoveryTime string `json:"recoveryTime,omitempty"`
}

type Database struct {
	// Roles assigned to users.
	Roles DatabaseRoles `json:"roles,omitempty"`
}

type DatabaseRoles struct {
	// List of users with admin privileges (readWrite + dbAdmin).
	Admin []string `json:"admin,omitempty"`
	// List of users with read-only privileges.
	Readonly []string `json:"readonly,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Shard struct {
	// Shard name.
	Name string `json:"name"`
	// Number of replicas in this shard.
	Replicas int `json:"replicas"`
	// PVC size for this shard.
	Size resource.Quantity `json:"size"`
}

type ShardingConfig struct {
	// PVC size for config servers.
	// +kubebuilder:default:="3Gi"
	ConfigServerSize resource.Quantity `json:"configServerSize"`
	// Number of config server replicas.
	// +kubebuilder:default:=3
	ConfigServers int `json:"configServers"`
	// Number of mongos router replicas.
	// +kubebuilder:default:=2
	Mongos int `json:"mongos"`
	// List of shard configurations.
	// +kubebuilder:default:={{"name":"rs0","replicas":3,"size":"10Gi"}}
	Shards []Shard `json:"shards,omitempty"`
}

type User struct {
	// Password for the user (auto-generated if omitted).
	Password string `json:"password,omitempty"`
}

// +kubebuilder:validation:Enum="nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v8";"v7";"v6"
type Version string
