// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package vpn

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of VPN server replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each VPN server replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="nano"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// Host used to substitute into generated URLs.
	// +kubebuilder:default:=""
	Host string `json:"host"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// List of externalIPs for service. Optional. If not specified, will use LoadBalancer service by default.
	// +kubebuilder:default:={}
	ExternalIPs []string `json:"externalIPs,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type User struct {
	// Password for the user (autogenerated if not provided).
	Password string `json:"password,omitempty"`
}

// +kubebuilder:validation:Enum="nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string
