// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package siterouter

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Site-to-site tunnel configuration.
	// +kubebuilder:default:={}
	Tunnel Tunnel `json:"tunnel"`
	// Remote peer of the tunnel.
	// +kubebuilder:default:={}
	Peer Peer `json:"peer"`
	// Remote networks reachable over the tunnel, at most 16. They must not overlap the cluster pod, service or join networks, node addresses or allocated LoadBalancer and external service addresses; an overlapping value is rejected.
	// +kubebuilder:default:={}
	// +kubebuilder:validation:MaxItems=16
	RemoteCIDRs []string `json:"remoteCIDRs,omitempty"`
	// Optional extra static routes programmed on the router.
	// +kubebuilder:default:={}
	StaticRoutes []StaticRoute `json:"staticRoutes,omitempty"`
	// Optional BGP peering over the tunnel. Disabled by default.
	// +kubebuilder:default:={}
	Bgp BGP `json:"bgp"`
	// Explicit CPU and memory sizing for the router VM.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// StorageClass for the router boot disk. Keep the `replicated` default where DRBD is available: only a DRBD-backed disk can live-migrate, and without live migration draining or losing the node drops the tunnel until the VM is rescheduled. Empty selects the cluster default StorageClass.
	// +kubebuilder:default:="replicated"
	StorageClass string `json:"storageClass"`
	// Opaque value mixed into the VM firmware UUID. Change it to make the router apply its first-boot configuration again; leave it empty to keep the existing VM's UUID.
	// +kubebuilder:default:=""
	CloudInitSeed string `json:"cloudInitSeed,omitempty"`
}

type BGP struct {
	// Enable BGP peering.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Local autonomous system number. Required when `enabled` is true; must be a valid ASN (1..4294967295).
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4.294967295e+09
	LocalASN int `json:"localASN,omitempty"`
	// BGP neighbors to peer with.
	Neighbors []BGPNeighbor `json:"neighbors,omitempty"`
}

type BGPNeighbor struct {
	// Neighbor IP address.
	// +kubebuilder:validation:Pattern="^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"
	Address string `json:"address"`
	// Remote autonomous system number of the neighbor. Must be a valid ASN (1..4294967295).
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4.294967295e+09
	RemoteASN int `json:"remoteASN"`
}

type Peer struct {
	// Public address (IP or hostname) the remote peer connects from. The remote peer starts the tunnel.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:Pattern="^[A-Za-z0-9.:-]*$"
	Address string `json:"address"`
	// IPsec authentication material for the tunnel.
	// +kubebuilder:default:={}
	Auth PeerAuth `json:"auth,omitempty"`
}

type PeerAuth struct {
	// Name of an existing Secret in the tenant namespace holding the pre-shared key (key `psk`). Takes precedence over `psk` when set.
	ExistingSecret string `json:"existingSecret,omitempty"`
	// IPsec pre-shared key. Autogenerated and stored in a Secret when omitted. Mutually exclusive with `existingSecret`.
	Psk string `json:"psk,omitempty"`
}

type Resources struct {
	// CPU cores allocated to the router VM, whole cores only and at least one. A fractional value such as "1500m" is rejected.
	// +kubebuilder:default:=2
	// +kubebuilder:validation:Minimum=1
	Cpu int `json:"cpu"`
	// Memory (RAM) allocated to the router VM.
	// +kubebuilder:default:="2Gi"
	Memory resource.Quantity `json:"memory"`
}

type StaticRoute struct {
	// Destination network in CIDR notation.
	// +kubebuilder:validation:Pattern="^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])/(3[0-2]|[12]?[0-9])$"
	Destination string `json:"destination"`
	// Next-hop IP address for the destination.
	// +kubebuilder:validation:Pattern="^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"
	NextHop string `json:"nextHop"`
}

type Tunnel struct {
	// Tunnel protocol used to connect to the remote peer.
	// +kubebuilder:default:="ipsec"
	Type TunnelType `json:"type"`
}

// +kubebuilder:validation:Enum="ipsec"
type TunnelType string
