---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cozystack-customizer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cozystack-customizer
    app.kubernetes.io/instance: {{ .Release.Name }}
