backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.6.2-rc.1@sha256:0774d068befce98dd067cb6239e5d37cb0b03b3d17a429e80caa46787d7f3726"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
