backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.5.0-rc.1@sha256:048863c3a16145a2f73e77be943e3936a7da9cce5e522c9ce10a3c0858ce79a7"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
