backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.4.4@sha256:6565567bb2a5f8f755da80ade86bb58c5479498dc27a2d1c765c4c26ea769aec"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
