apiVersion: v2
name: gateway
description: Cozystack per-tenant Gateway API resource backed by Cilium
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
