cilium:
  kubeProxyReplacement: true
  hostFirewall:
    enabled: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
    serviceTopology: true
  ipam:
    mode: "kubernetes"
  image:
    repository: ghcr.io/cozystack/cozystack/cilium
    tag: 1.19.1
    digest: "sha256:ab3acf270821df4614a8456348a4e0d3098aed72a4b2016a0edfa30d91428c3d"
  envoy:
    enabled: false
  rollOutCiliumPods: true
  operator:
    rollOutPods: true
    replicas: 1
