cilium:
  kubeProxyReplacement: true
  hostFirewall:
    enabled: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
    serviceTopology: true
  ipam:
    mode: "kubernetes"
  image:
    repository: ghcr.io/cozystack/cozystack/cilium
    tag: 1.19.3
    digest: "sha256:700f06f4803a838a8e830be5ace4650e3ad82bdefabfb2f4d110368d307a5efb"
  envoy:
    enabled: false
  rollOutCiliumPods: true
  operator:
    rollOutPods: true
    replicas: 1
