{{- if ne (include "tenant.name" .) "tenant-root" }}
{{- $sourceSecret := lookup "v1" "Secret" "cozy-system" "patch-containerd" }}
{{- if $sourceSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: patch-containerd
  namespace: {{ include "tenant.name" . }}
type: {{ $sourceSecret.type }}
data:
{{- range $key, $value := $sourceSecret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
