{{ $volumes := (list .Values.volume) }}
{{- range .Values.volumes }}
{{ $volumes = append $volumes (deepCopy . | mergeOverwrite $.Values.volume) }}
{{- end }}

{{- range $index, $volume := $volumes }}
{{- $volumeName := printf "volume%d" $index }}
{{- if eq $index 0 }}
{{- $volumeName = "volume" }}
{{- end }}
{{- if $volume.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" $ }}-{{ $volumeName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" $ }}
    app.kubernetes.io/component: volume
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  clusterIP: None
  internalTrafficPolicy: {{ $volume.internalTrafficPolicy | default "Cluster" }}
  ports:
  - name: "swfs-volume"
    port: {{ $volume.port }}
    targetPort: {{ $volume.port }}
    protocol: TCP
  - name: "swfs-volume-18080"
    port: {{ $volume.grpcPort }}
    targetPort: {{ $volume.grpcPort }}
    protocol: TCP
{{- if $volume.metricsPort }}
  - name: "metrics"
    port: {{ $volume.metricsPort }}
    targetPort: {{ $volume.metricsPort }}
    protocol: TCP
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "seaweedfs.name" $ }}
    app.kubernetes.io/component: volume
{{- end }}
{{- end }}
