---
apiVersion: v1
kind: Secret
metadata:
  name: cozystack-values
  namespace: tenant-root
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  values.yaml: |
    _cluster:
      oidc-enabled: {{ .Values.oidcEnabled | quote }}
      root-host: {{ .Values.rootHost | quote }}
    _namespace:
      host: {{ .Values.rootHost | quote }}
