securityGroupController:
  image: "ghcr.io/cozystack/cozystack/securitygroup-controller:v1.7.0-alpha.3@sha256:896159f9efb899fbd740612f98d400a821569b7b3beb62d764686524d308674b"
  replicas: 2
  debug: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
