securityGroupController:
  image: "ghcr.io/cozystack/cozystack/securitygroup-controller:v1.6.1-rc.1@sha256:1eaaed61b595ed79460709a410d1da830031e82926b0a2fd8cfd917e0e120844"
  replicas: 2
  debug: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
