---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.hami
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.gpu-operator
    components:
    - name: hami
      path: system/hami
      valuesFiles:
      - values.yaml
      install:
        privileged: true
        namespace: cozy-hami
        releaseName: hami
