// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package kafka

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sRuntime "k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// Kafka version to deploy.
	// +kubebuilder:default:="v3.9"
	Version Version `json:"version"`
	// Topics configuration.
	// +kubebuilder:default:={}
	Topics []Topic `json:"topics,omitempty"`
	// Kafka configuration.
	// +kubebuilder:default:={}
	Kafka Kafka `json:"kafka"`
	// ZooKeeper configuration (only used for existing instances migrating from ZooKeeper to KRaft).
	// +kubebuilder:default:={}
	Zookeeper ZooKeeper `json:"zookeeper,omitempty"`
}

type Kafka struct {
	// Persistent Volume size for KRaft controller metadata (used during ZK-to-KRaft migration).
	// +kubebuilder:default:="5Gi"
	ControllerStorageSize resource.Quantity `json:"controllerStorageSize,omitempty"`
	// Number of Kafka replicas.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume size for Kafka.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the Kafka data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Topic struct {
	// Topic configuration.
	Config k8sRuntime.RawExtension `json:"config"`
	// Topic name.
	Name string `json:"name"`
	// Number of partitions.
	Partitions int `json:"partitions"`
	// Number of replicas.
	Replicas int `json:"replicas"`
}

type ZooKeeper struct {
	// Number of ZooKeeper replicas.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume size for ZooKeeper.
	// +kubebuilder:default:="5Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the ZooKeeper data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
}

// +kubebuilder:validation:Enum="nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v3.9";"v3.8"
type Version string
