// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package kafka

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sRuntime "k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// Reserved addresses for the endpoints `external: true` publishes. Each entry pins one endpoint to an address held by an IPAddressClaim, so the address survives a rebuild of this application. Empty lets the load balancer assign any free address, as before.
	// +kubebuilder:default:={}
	ExternalIPs []ExternalIP `json:"externalIPs,omitempty"`
	// TLS configuration. Strimzi manages the cluster PKI automatically (no cert-manager is involved for this chart): the operator auto-creates `<release>-cluster-ca-cert` and `<release>-clients-ca-cert` secrets, both exposed for client trust setup. The internal TLS listener on 9093 is always on; this toggle only controls the external listener on 9094.
	// +kubebuilder:default:={}
	Tls TLS `json:"tls"`
	// Topics configuration.
	// +kubebuilder:default:={}
	Topics []Topic `json:"topics,omitempty"`
	// Users of the cluster, each backed by a Strimzi KafkaUser. Declaring at least one user turns on SCRAM-SHA-512 authentication on every listener and ACL authorization for the whole cluster, so clients that connected without credentials lose access. The username is `<release>-<key>`; Strimzi generates the password into the Secret of the same name (keys `password` and `sasl.jaas.config`). Keys must be lowercase DNS labels.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Kafka configuration.
	// +kubebuilder:default:={}
	Kafka Kafka `json:"kafka"`
	// KRaft controller configuration. The controllers hold the cluster metadata that ZooKeeper used to hold; the brokers are configured under `kafka`.
	// +kubebuilder:default:={}
	Controller Controller `json:"controller"`
}

type ACL struct {
	// Name of the topic, consumer group or transactional id the rule covers, or its prefix when `patternType` is `prefix`. Not used for `cluster`.
	Name string `json:"name,omitempty"`
	// Operations the rule allows on the resource.
	Operations []ACLOperation `json:"operations"`
	// `literal` (the default) matches `name` exactly, `prefix` matches every resource whose name starts with it.
	PatternType ACLPatternType `json:"patternType,omitempty"`
	// Kind of resource the rule covers.
	Resource ACLResource `json:"resource"`
}

type Controller struct {
	// Number of KRaft controllers. Use an odd number: the metadata quorum needs a majority of them.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="c1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume size for the metadata log of each controller.
	// +kubebuilder:default:="5Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the controller metadata.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
}

type ExternalIP struct {
	// Name of an IPAddressClaim in this namespace whose address the endpoint should wear. Until the claim binds, the endpoint keeps whatever address the load balancer assigned.
	Claim string `json:"claim"`
	// Which external endpoint to pin: `bootstrap` (the default) for the bootstrap Service clients connect to first, or `broker-N` for the per-broker Service of broker N. Kafka advertises every broker's own address, so pinning the bootstrap address alone does not make the whole cluster reachable at fixed addresses — pin one entry per broker for that.
	Target string `json:"target,omitempty"`
}

type Kafka struct {
	// Number of Kafka replicas.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="c1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume size for Kafka.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the Kafka data.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type TLS struct {
	// Enable TLS on the external listener. When unset, inherits the value of `external` (TLS is on when external access is enabled). Warning: setting this to false while external is true exposes Kafka over plaintext on a public IP via LoadBalancer. Strimzi does not provide authentication on this listener unless SCRAM, mTLS, or OAuth is separately configured. Use only in controlled networks.
	Enabled *bool `json:"enabled,omitempty"`
}

type Topic struct {
	// Topic configuration.
	Config k8sRuntime.RawExtension `json:"config"`
	// Topic name.
	Name string `json:"name"`
	// Number of partitions.
	Partitions int `json:"partitions"`
	// Number of replicas.
	Replicas int `json:"replicas"`
}

type User struct {
	// Access rules of the user. A user without rules can authenticate but is denied everything.
	Acls []ACL `json:"acls,omitempty"`
}

// +kubebuilder:validation:Enum="Read";"Write";"Create";"Delete";"Alter";"Describe";"ClusterAction";"AlterConfigs";"DescribeConfigs";"IdempotentWrite";"All"
type ACLOperation string

// +kubebuilder:validation:Enum="literal";"prefix"
type ACLPatternType string

// +kubebuilder:validation:Enum="topic";"group";"cluster";"transactionalId"
type ACLResource string

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string
