kilo:
  image:
    pullPolicy: IfNotPresent
    tag: 0.7.0@sha256:c7468aee96425f47369fd1d33b9736147aebc2e9c6e4355d0593461c30af308e
    repository: ghcr.io/squat/kilo
  transitCIDR: 100.66.0.0/16
  meshGranularity: location
  cleanUpInterface: false
  mtu: auto
