kilo:
  image:
    pullPolicy: IfNotPresent
    tag: v1.5.0@sha256:fe837f428504f6c6e9e4582326a3bf9cd507a9cca58c975952f5cc0b34728f63
    repository: ghcr.io/cozystack/cozystack/kilo
  transitCIDR: 100.66.0.0/16
  meshGranularity: location
  cleanUpInterface: false
  mtu: auto
