kilo:
  image:
    pullPolicy: IfNotPresent
    tag: v1.7.0-alpha.3@sha256:4890b8496461b22713449c23c1b870121c975efc1f5611de682646d37cfcbd42
    repository: ghcr.io/cozystack/cozystack/kilo
  transitCIDR: 100.66.0.0/16
  meshGranularity: location
  cleanUpInterface: false
  mtu: auto
