{{- range .Values.logsStorages }}
---
apiVersion: operator.victoriametrics.com/v1
kind: VLCluster
metadata:
  name: {{ .name }}
spec:
  managedMetadata:
    labels:
      apps.cozystack.io/application.group: apps.cozystack.io
      apps.cozystack.io/application.kind: Monitoring
      apps.cozystack.io/application.name: {{ $.Release.Name }}
  vlinsert:
    replicaCount: 2
    resources: {}
  vlselect:
    replicaCount: 2
    resources: {}
  vlstorage:
    retentionPeriod: {{ .retentionPeriod | quote }}
    replicaCount: 2
    resources: {}
    storage:
      volumeClaimTemplate:
        spec:
          {{- with .storageClassName }}
          storageClassName: {{ . }}
          {{- end }}
          resources:
            requests:
              storage: {{ .storage }}
{{- end }}
