---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: victoria-metrics-operator-cadvisor
  namespace: cozy-monitoring
spec:
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  honorLabels: true
  interval: 30s
  metricRelabelConfigs:
    - action: labeldrop
      regex: (uid)
    - action: labeldrop
      regex: (id|name)
    - action: drop
      regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
      source_labels: [__name__]
    - action: keep
      regex: (container_cpu_usage_seconds_total|container_memory_usage_bytes|container_network_.*|container_fs_.*|container_spec_cpu_quota|container_spec_memory_limit_bytes|container_cpu_cfs_throttled_(periods_total|seconds_total)|container_cpu_cfs_periods_total|container_memory_working_set_bytes|container_memory_cache|container_memory_rss|container_memory_swap|container_cpu_system_seconds_total|container_cpu_user_seconds_total|container_oom_events_total)
      source_labels: [__name__]
  path: /metrics/cadvisor
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - action: labeldrop
      regex: '.*node_kubevirt_io.*'
    - sourceLabels: [__metrics_path__]
      targetLabel: metrics_path
    - replacement: cadvisor
      targetLabel: job
  scheme: https
  scrapeTimeout: 5s
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
