{{- $host := index .Values._cluster "root-host" }}
{{- $exposeServices := splitList "," ((index .Values._cluster "expose-services") | default "") }}
{{- $exposeIngress := (index .Values._cluster "expose-ingress") | default "tenant-root" }}
{{- $gatewayEnabled := (index .Values._cluster "gateway-enabled") | default "false" }}
{{- if and (has "cdi-uploadproxy" $exposeServices) (eq $gatewayEnabled "true") }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: cdi-uploadproxy
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cozystack
    namespace: {{ $exposeIngress }}
    sectionName: tls-cdi-uploadproxy
  hostnames:
  - {{ printf "cdi-uploadproxy.%s" $host | quote }}
  rules:
  - backendRefs:
    - name: cdi-uploadproxy
      port: 443
{{- end }}
