kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.1.7@sha256:5c76d87565a208786e6f745e707578d061284dca827ed1ca6e47aa4ae8693a97
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.1.7@sha256:5c76d87565a208786e6f745e707578d061284dca827ed1ca6e47aa4ae8693a97
