kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.3.1@sha256:8c727e4eb9500f7dd1c76b6daf7bb5e6cfee1984dfb79e0a8fc4c4b467937f86
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  startupProbe:
    httpGet:
      path: /healthz
      port: healthcheck
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 12
  livenessProbe:
    httpGet:
      path: /healthz
      port: healthcheck
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: healthcheck
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.3.1@sha256:8c727e4eb9500f7dd1c76b6daf7bb5e6cfee1984dfb79e0a8fc4c4b467937f86
