// +kubebuilder:object:generate=true
// +kubebuilder:object:root=true
// +groupName=values.helm.io

// +versionName=v1alpha1

// Code generated by values-gen. DO NOT EDIT.
package clickhouse

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
	// ClickHouse Keeper configuration.
	// +kubebuilder:default:={}
	ClickhouseKeeper ClickHouseKeeper `json:"clickhouseKeeper"`
	// Size of Persistent Volume for logs.
	// +kubebuilder:default:="2Gi"
	LogStorageSize resource.Quantity `json:"logStorageSize"`
	// TTL (expiration time) for `query_log` and `query_thread_log`.
	// +kubebuilder:default:=15
	LogTTL int `json:"logTTL"`
	// Number of ClickHouse replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each ClickHouse replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Number of ClickHouse shards.
	// +kubebuilder:default:=1
	Shards int `json:"shards"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
}

type ClickHouseKeeper struct {
	// Deploy ClickHouse Keeper for cluster coordination.
	// +kubebuilder:default:=true
	Enabled bool `json:"enabled,omitempty"`
	// Number of Keeper replicas.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas,omitempty"`
	// Default sizing preset.
	// +kubebuilder:default:="micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset,omitempty"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="1Gi"
	Size resource.Quantity `json:"size,omitempty"`
}

type User struct {
	// Password for the user.
	Password string `json:"password,omitempty"`
	// User is readonly (default: false).
	Readonly bool `json:"readonly,omitempty"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Backup struct {
	// Retention strategy for cleaning up old backups.
	// +kubebuilder:default:="--keep-last=3 --keep-daily=3 --keep-within-weekly=1m"
	CleanupStrategy string `json:"cleanupStrategy"`
	// Enable regular backups (default: false).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Password for Restic backup encryption.
	// +kubebuilder:default:="<password>"
	ResticPassword string `json:"resticPassword"`
	// Access key for S3 authentication.
	// +kubebuilder:default:="<your-access-key>"
	S3AccessKey string `json:"s3AccessKey"`
	// S3 bucket used for storing backups.
	// +kubebuilder:default:="s3.example.org/clickhouse-backups"
	S3Bucket string `json:"s3Bucket"`
	// AWS S3 region where backups are stored.
	// +kubebuilder:default:="us-east-1"
	S3Region string `json:"s3Region"`
	// Secret key for S3 authentication.
	// +kubebuilder:default:="<your-secret-key>"
	S3SecretKey string `json:"s3SecretKey"`
	// Cron schedule for automated backups.
	// +kubebuilder:default:="0 2 * * *"
	Schedule string `json:"schedule"`
}

// +kubebuilder:validation:Enum="nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string
