{
 "title": "Capacity Planning",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\"}, namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{node=~\"$node\", condition=\"Ready\", status=\"true\"} == 1)"
    }
   ]
  },
  {
   "title": "All Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (namespace) (kube_namespace_status_phase{namespace=~\"$namespace\", phase=\"Active\"}))"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 0 },
   "options": {
    "content": "✓ If you have pods in pending state in your cluster, it can be caused because the scheduler cannot find a node with enough memory and CPU allocatable. <br>\n✓ Check that you have at least 1 node in your cluster with enough allocatable CPU and memory to accomplish the requests of the pending pods. <b>Be sure that the node with enough resources has not a taint or is not unscheduleable.</b> <br>\n✓ Check that that node has pods available to schedule in it. <br>\n✓ If the nodes ran out of allocatable resources you can try to adjust the requests of your pods to optimize the capacity of your nodes using the Memory Allocation Optimization and CPU Allocation Optimization dashboards. If this is not possible, you will have to increase the number of nodes in your cluster. <br>\n✓ If there are enough resources in the nodes, go to the Main folder dashboards and check the available resource in the quotas of the namespace."
   }
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "% Requested CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval])* on (namespace, pod) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1))) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "% Requested Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"}[$__rate_interval])* on (namespace, pod) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1))) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "% Actual CPU Usage",
   "type": "gauge",
   "description": "How much CPU is actually used in the cluster (CPU usage / Allocatable CPU).",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"\",node=~\"$node\"}[$__rate_interval])))\n / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "% Actual Memory Usage",
   "type": "gauge",
   "description": "How much memory is actually used in the cluster (Memory usage / Allocatable Memory).",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (node) (container_memory_working_set_bytes:without_kmem{container!=\"\",node=~\"$node\"})) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "% Used Requested CPU",
   "type": "gauge",
   "description": "How many requested cores are used (Actual CPU / Requested CPU).",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"\",node=~\"$node\"}[$__rate_interval]))) / sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "% Used Requested Memory",
   "type": "gauge",
   "description": "How much requested memory is used (Actual Memory / Requested Memory). ",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (node) (container_memory_working_set_bytes:without_kmem{container!=\"\",node=~\"$node\"} )) / sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Pods Usage",
   "type": "gauge",
   "description": "Pods number in the cluster / Allocatable Pods.",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((max by (pod, namespace)(kube_pod_container_status_running))==1) * on (pod, namespace) group_right() (kube_pod_info{node=~\"$node\"}==1) \n) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Allocatable / Requested / Unused",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Allocatable CPU",
   "type": "timeseries",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unrequested CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"}[$__rate_interval])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval])* on (namespace, pod) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)) or sum by (node) (kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"} * 0))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"}[$__rate_interval])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=~\"$node\"}[$__rate_interval])* on (namespace, pod) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)) or sum by (node) (kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"} * 0)))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unused Requested CPU (Idle)",
   "type": "timeseries",
   "description": "Difference between requested cores and used cores.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"\",node=~\"$node\"}[$__rate_interval]) - on (namespace,pod,container,node) group_left avg by (namespace,pod,container, node)(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})) * -1 > 0\n",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"\",node=~\"$node\"}[$__rate_interval]) - on (namespace,pod,container,node) group_left avg by (namespace,pod,container, node)(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})) * -1 > 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "timeseries",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unrequested Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"}[$__rate_interval])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"}[$__rate_interval])* on (namespace, pod) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)) or sum by (node) (kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"} * 0))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"}[$__rate_interval])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"}[$__rate_interval])* on (namespace, pod) group_left(phase) (kube_pod_status_phase{phase=\"Running\"} == 1)) or sum by (node) (kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"} * 0)))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unused Requested Memory",
   "type": "timeseries",
   "description": "Difference between requested memory and used memory.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum by (node) (container_memory_working_set_bytes:without_kmem{container!=\"\",node=~\"$node\"} ) - sum by (node) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})) * -1 > 0\n",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum((sum by (node) (container_memory_working_set_bytes:without_kmem{container!=\"\",node=~\"$node\"} ) - sum by (node) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})) * -1 > 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Allocatable Pods",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Available Pod slots",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"}[$__rate_interval])) - on(node) (count by (node) (\n  ((max by (pod, namespace)(kube_pod_container_status_running))==1) * on (pod, namespace) group_right() (kube_pod_info{node=~\"$node\"}==1) \n))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"}[$__rate_interval])) - on(node) (count by (node) (\n  ((max by (pod, namespace)(kube_pod_container_status_running))==1) * on (pod, namespace) group_right() (kube_pod_info{node=~\"$node\"}==1) \n)))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Top 10 CPU overrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "topk(10, (sum by (namespace,pod,container)((rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container!=\"\",node=~\"$node\"}[$__rate_interval])) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"}))) * -1 > 0)\n"
    }
   ]
  },
  {
   "title": "Top 10 Memory overrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "topk(10, (sum by (namespace,container,pod) (container_memory_working_set_bytes:without_kmem{container!=\"\",namespace=~\"$namespace\",node=~\"$node\"}) - on (namespace,pod,container) avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\",node=~\"$node\"})) * -1 >0)\n"
    }
   ]
  },
  {
   "title": "Top 10 CPU underrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "topk(10, (sum by (namespace,pod,container)((rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container!=\"\",node=~\"$node\"}[$__rate_interval])) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"}))) > 0)\n"
    }
   ]
  },
  {
   "title": "Top 10 Memory underrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "topk(10, (sum by (namespace,container,pod) (container_memory_working_set_bytes:without_kmem{container!=\"\",namespace=~\"$namespace\",node=~\"$node\"}) - on (namespace,pod,container) avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\",node=~\"$node\"})) >0)\n"
    }
   ]
  }
 ]
}