apiVersion: apps.cozystack.io/v1alpha1
kind: Kubernetes
metadata:
  name: oidc-system
spec:
  addons:
    ingressNginx:
      enabled: false
      hosts: []
      valuesOverride: {}
  controlPlane:
    apiServer:
      resources: {}
      resourcesPreset: small
    replicas: 1
  nodeGroups:
    md0:
      diskSize: 20Gi
      gpus: []
      instanceType: u1.micro
      maxReplicas: 1
      minReplicas: 0
      resources: {}
      roles:
      - worker
  storageClass: replicated
  version: v1.35
  oidc:
    mode: System
    users:
    - email: e2e-admin@example.test
      role: admin
    - email: e2e-viewer@example.test
      role: view
