{{- if .Values.registries.mirrors }}
apiVersion: v1
kind: Secret
metadata:
  name: patch-containerd
  namespace: cozy-system
type: Opaque
stringData:
{{- range $registry, $mirror := .Values.registries.mirrors }}
{{- if $mirror.endpoints }}
  {{ $registry }}.toml: |
    server = "https://{{ $registry }}"
{{- range $endpoint := $mirror.endpoints }}
    [host."{{ $endpoint }}"]
      capabilities = ["pull", "resolve"]
{{- $endpointWithoutScheme := $endpoint | trimPrefix "https://" | trimPrefix "http://" }}
{{- $endpointWithUnderscore := replace ":" "_" $endpointWithoutScheme }}
{{- $endpointConfig := or (index $.Values.registries.config $endpointWithoutScheme) (index $.Values.registries.config $endpointWithUnderscore) }}
{{- if $endpointConfig }}
{{- if $endpointConfig.tls }}
{{- if $endpointConfig.tls.insecureSkipVerify }}
      skip_verify = true
{{- end }}
{{- end }}
{{- if $endpointConfig.auth }}
      [host."{{ $endpoint }}".auth]
        username = "{{ $endpointConfig.auth.username }}"
        password = "{{ $endpointConfig.auth.password }}"
{{- end }}
{{- else }}
      skip_verify = true
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

