---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cozystack-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cozystack-controller
subjects:
- kind: ServiceAccount
  name: cozystack-controller
  namespace: cozy-system
